# Day 09. Exercise 00
# Regularization

## 0. Imports

In [82]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

## 1. Preprocessing

1. Read the file `dayofweek.csv` that you used in the previous day to a dataframe.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [83]:
df = pd.read_csv("../data/dayofweek.csv")
df

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek
0,-0.788667,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
1,-0.756764,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
2,-0.724861,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
3,-0.692958,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
4,-0.661055,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,-0.533442,0.945382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
1682,-0.629151,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
1683,-0.597248,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
1684,-0.565345,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
1685,-0.533442,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3

In [84]:
y = df['dayofweek'] #таргет
X = df.drop(columns=['dayofweek']) #features
y

0       4
1       4
2       4
3       4
4       4
       ..
1681    3
1682    3
1683    3
1684    3
1685    3
Name: dayofweek, Length: 1686, dtype: int64

In [85]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=21,stratify=y) #stratify позволяет
# сохранять % каждого класса в train и test равномерно
X_train

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
860,-0.724861,-0.691561,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
385,-0.629151,-1.159259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
422,-0.788667,-1.393108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
326,-0.533442,0.945382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
714,0.678880,-0.925410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,-0.501539,0.009986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1637,-0.756764,-0.457712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1334,1.444556,-0.691561,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
979,0.742686,0.711533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1241,0.104622,0.945382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## 2. Logreg regularization

### a. Default regularization

1. Train a baseline model with the only parameters `random_state=21`, `fit_intercept=False`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model


The result of the code where you trained and evaluated the baseline model should be exactly like this (use `%%time` to get the info about how long it took to run the cell):

```
train -  0.62902   |   valid -  0.59259
train -  0.64633   |   valid -  0.62963
train -  0.63479   |   valid -  0.56296
train -  0.65622   |   valid -  0.61481
train -  0.63397   |   valid -  0.57778
train -  0.64056   |   valid -  0.59259
train -  0.64138   |   valid -  0.65926
train -  0.65952   |   valid -  0.56296
train -  0.64333   |   valid -  0.59701
train -  0.63674   |   valid -  0.62687
Average accuracy on crossval is 0.60165
Std is 0.02943
```

In [86]:
def crossval(estimator, X, y, n_splits=10): #estimator - модель 
    train_scores = []
    valid_scores = [] #обобщение, рез-т работы на новых данных
    cv = StratifiedKFold(n_splits=n_splits) #кросс-валидатор, каждый fold - n_splits разбивает выборку train на кол-во n
    
    for train, valid in cv.split(X, y): #cv.split(X, y) генератор пар массивов (train, valid) при n_splits = 10 мы передаем по факту X_train, y_train 
        X_tr = X.iloc[train]   # Берёт строки 135, 136, ..., 1350 из X    это все для 1-й иттерации
        X_val = X.iloc[valid]  # Берёт строки 0, 1, ..., 134 из X
        y_tr = y.iloc[train]   # Берёт строки 135, 136, ..., 1350 из y
        y_val = y.iloc[valid]  # Берёт строки 0, 1, ..., 134 из y

        estimator.fit(X_tr, y_tr)
        y_train_pred = estimator.predict(X_tr)
        y_valid_pred = estimator.predict(X_val)
        
        train_scores.append(accuracy_score(y_tr, y_train_pred))
        valid_scores.append(accuracy_score(y_val, y_valid_pred))
    
    for train, valid in zip(train_scores, valid_scores): #списки в пары
        print(f'train -  {train:.5f}   |   valid -  {valid:.5f}')
    
    print(f'Average accuracy on crossval is {np.mean(valid_scores):.5f}')
    print(f'Std is {np.std(valid_scores):.5f}')

logreg = LogisticRegression(fit_intercept=False, random_state=21)
crossval(logreg, X_train, y_train)

train -  0.62902   |   valid -  0.59259
train -  0.64633   |   valid -  0.62963
train -  0.63479   |   valid -  0.56296
train -  0.65622   |   valid -  0.61481
train -  0.63397   |   valid -  0.57778
train -  0.64056   |   valid -  0.59259
train -  0.64138   |   valid -  0.65926
train -  0.65952   |   valid -  0.56296
train -  0.64333   |   valid -  0.59701
train -  0.63674   |   valid -  0.62687
Average accuracy on crossval is 0.60165
Std is 0.02943

### b. Optimizing regularization parameters

1. In the cells below try different values of penalty: `none`, `l1`, `l2` – you can change the values of solver too.

In [87]:
logreg_none = LogisticRegression( 
    penalty='none', #миним пенальти
    solver='lbfgs',      # работает с 'none' и 'l2'
    fit_intercept=False,
    random_state=21,
    max_iter=1000
)
score_none = crossval(logreg_none, X_train, y_train)

train -  0.66694   |   valid -  0.63704
train -  0.65787   |   valid -  0.65926
train -  0.66694   |   valid -  0.57778
train -  0.66529   |   valid -  0.62963
train -  0.66694   |   valid -  0.62222
train -  0.65952   |   valid -  0.57778
train -  0.65045   |   valid -  0.69630
train -  0.68425   |   valid -  0.61481
train -  0.66474   |   valid -  0.62687
train -  0.65651   |   valid -  0.60448
Average accuracy on crossval is 0.62462
Std is 0.03379

In [88]:
logreg_l2 = LogisticRegression( #С - параметр регуляризации
    penalty='l2', #сжатие + такие настройки стоят по дефолту 
    C=1,
    solver='lbfgs',      # работает с 'l2'
    fit_intercept=False,
    random_state=21,
    max_iter=1000
)
score_l2 = crossval(logreg_l2, X_train, y_train)
# Штраф L2 = w₁² + w₂² + w₃² + ... + wₙ²
# w = [2, -3, 1]
# L2 штраф = 2² + (-3)² + 1² = 4 + 9 + 1 = 14

train -  0.62902   |   valid -  0.59259
train -  0.64633   |   valid -  0.62963
train -  0.63479   |   valid -  0.56296
train -  0.65622   |   valid -  0.61481
train -  0.63397   |   valid -  0.57778
train -  0.64056   |   valid -  0.59259
train -  0.64138   |   valid -  0.65926
train -  0.65952   |   valid -  0.56296
train -  0.64333   |   valid -  0.59701
train -  0.63674   |   valid -  0.62687
Average accuracy on crossval is 0.60165
Std is 0.02943

In [89]:
logreg_l1 = LogisticRegression(
    penalty='l1', #вес обнуляется и выкидывается из модели
    C=1,
    solver='liblinear',  # работает с 'l1' и 'l2'
    fit_intercept=False,
    random_state=21,
    max_iter=1000
)
score_l1 = crossval(logreg_l1, X_train, y_train)
# Штраф L1 = |w₁| + |w₂| + |w₃| + ... + |wₙ|
#w = [2, -3, 1]
#L1 штраф = |2| + |-3| + |1| = 2 + 3 + 1 = 6

train -  0.61830   |   valid -  0.54815
train -  0.62737   |   valid -  0.62222
train -  0.60511   |   valid -  0.54074
train -  0.63644   |   valid -  0.62222
train -  0.62407   |   valid -  0.55556
train -  0.62325   |   valid -  0.58519
train -  0.61253   |   valid -  0.63704
train -  0.64716   |   valid -  0.58519
train -  0.63015   |   valid -  0.59701
train -  0.61367   |   valid -  0.59701
Average accuracy on crossval is 0.58903
Std is 0.03129

## 3. SVM regularization

### a. Default regularization

1. Train a baseline model with the only parameters `probability=True`, `kernel='linear'`, `random_state=21`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model.
3. The format of the result of the code where you trained and evaluated the baseline model should be similar to what you have got for the logreg.

In [90]:
%%time
svm_baseline = SVC(
    probability=True,
    kernel='linear',
    random_state=21,
)
svm_score = crossval(svm_baseline, X_train, y_train)

train -  0.70486   |   valid -  0.65926
train -  0.69662   |   valid -  0.75556
train -  0.69415   |   valid -  0.62222
train -  0.70239   |   valid -  0.65185
train -  0.69085   |   valid -  0.65185
train -  0.68920   |   valid -  0.64444
train -  0.69250   |   valid -  0.72593
train -  0.70074   |   valid -  0.62222
train -  0.69605   |   valid -  0.61940
train -  0.71087   |   valid -  0.63433
Average accuracy on crossval is 0.65871
Std is 0.04359
CPU times: total: 2.95 s
Wall time: 2.98 s

### b. Optimizing regularization parameters

1. In the cells below try different values of the parameter `C`.

In [91]:
C_values = [0.1, 1.0, 10.0]
svm_results = []

for C in C_values:
    print(f"C = {C}")
    
    svm_model = SVC(
        probability=True,
        kernel='linear',
        C=C,
        random_state=21
    )

    score = crossval(svm_model, X_train, y_train)
    svm_results.append({'C': C, 'accuracy': score})

C = 0.1
train -  0.58120   |   valid -  0.55556
train -  0.57543   |   valid -  0.56296
train -  0.57378   |   valid -  0.57037
train -  0.59275   |   valid -  0.57037
train -  0.58120   |   valid -  0.54815
train -  0.57955   |   valid -  0.54815
train -  0.57296   |   valid -  0.61481
train -  0.59192   |   valid -  0.54815
train -  0.59967   |   valid -  0.52985
train -  0.57825   |   valid -  0.57463
Average accuracy on crossval is 0.56230
Std is 0.02177
C = 1.0
train -  0.70486   |   valid -  0.65926
train -  0.69662   |   valid -  0.75556
train -  0.69415   |   valid -  0.62222
train -  0.70239   |   valid -  0.65185
train -  0.69085   |   valid -  0.65185
train -  0.68920   |   valid -  0.64444
train -  0.69250   |   valid -  0.72593
train -  0.70074   |   valid -  0.62222
train -  0.69605   |   valid -  0.61940
train -  0.71087   |   valid -  0.63433
Average accuracy on crossval is 0.65871
Std is 0.04359
C = 10.0
train -  0.75021   |   valid -  0.72593
train -  0.77741   |   valid -  0.82963
train -  0.78566   |   valid -  0.68148
train -  0.76834   |   valid -  0.73333
train -  0.75185   |   valid -  0.77778
train -  0.75598   |   valid -  0.68889
train -  0.76257   |   valid -  0.74074
train -  0.77411   |   valid -  0.68889
train -  0.78254   |   valid -  0.71642
train -  0.78418   |   valid -  0.69403
Average accuracy on crossval is 0.72771
Std is 0.04417

## 4. Tree

### a. Default regularization

1. Train a baseline model with the only parameter `max_depth=10` and `random_state=21`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model.
3. The format of the result of the code where you trained and evaluated the baseline model should be similar to what you have got for the logreg.

In [92]:
# %%time
tree = DecisionTreeClassifier(max_depth=10, random_state=21)
crossval(tree, X_train, y_train) #может разнится для 0.23.1/0.23.2 т.к происходит tie breaking ( как раз-таки по этому числовые столбцы должны быть первее чем категориальные, т.к берут самое первое различное значение при tie-breaking)

train -  0.81039   |   valid -  0.74074
train -  0.77741   |   valid -  0.74074
train -  0.83347   |   valid -  0.70370
train -  0.79720   |   valid -  0.76296
train -  0.82440   |   valid -  0.75556
train -  0.80379   |   valid -  0.68889
train -  0.80709   |   valid -  0.76296
train -  0.80132   |   valid -  0.65926
train -  0.80807   |   valid -  0.75373
train -  0.80478   |   valid -  0.68657
Average accuracy on crossval is 0.72551
Std is 0.03562

### b. Optimizing regularization parameters

1. In the cells below try different values of the parameter `max_depth`.
2. As a bonus, play with other regularization parameters trying to find the best combination.

In [93]:
depth_values = [9, 10, 20, None]

tree_results = []

for depth in depth_values:
    print(f"max_depth = {depth}")
    tree_model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=21
    )
    
    score = crossval(tree_model, X_train, y_train)
    tree_results.append({'max_depth': depth, 'accuracy': score})

max_depth = 9
train -  0.76587   |   valid -  0.72593
train -  0.74444   |   valid -  0.74815
train -  0.78236   |   valid -  0.62963
train -  0.74691   |   valid -  0.74815
train -  0.79143   |   valid -  0.72593
train -  0.77494   |   valid -  0.65185
train -  0.76999   |   valid -  0.74074
train -  0.76587   |   valid -  0.67407
train -  0.77677   |   valid -  0.71642
train -  0.76771   |   valid -  0.67164
Average accuracy on crossval is 0.70325
Std is 0.04068
max_depth = 10
train -  0.81039   |   valid -  0.74074
train -  0.77741   |   valid -  0.74074
train -  0.83347   |   valid -  0.70370
train -  0.79720   |   valid -  0.76296
train -  0.82440   |   valid -  0.75556
train -  0.80379   |   valid -  0.68889
train -  0.80709   |   valid -  0.76296
train -  0.80132   |   valid -  0.65926
train -  0.80807   |   valid -  0.75373
train -  0.80478   |   valid -  0.68657
Average accuracy on crossval is 0.72551
Std is 0.03562
max_depth = 20
train -  0.98846   |   valid -  0.86667
train -  0.99011   |   valid -  0.91111
train -  0.98681   |   valid -  0.85926
train -  0.98763   |   valid -  0.91111
train -  0.98928   |   valid -  0.88148
train -  0.98186   |   valid -  0.85926
train -  0.98846   |   valid -  0.91852
train -  0.99176   |   valid -  0.89630
train -  0.99094   |   valid -  0.88060
train -  0.98847   |   valid -  0.88060
Average accuracy on crossval is 0.88649
Std is 0.02075
max_depth = None
train -  1.00000   |   valid -  0.85926
train -  1.00000   |   valid -  0.91852
train -  1.00000   |   valid -  0.86667
train -  1.00000   |   valid -  0.91111
train -  1.00000   |   valid -  0.88148
train -  1.00000   |   valid -  0.85185
train -  1.00000   |   valid -  0.92593
train -  1.00000   |   valid -  0.88148
train -  1.00000   |   valid -  0.88060
train -  1.00000   |   valid -  0.88060
Average accuracy on crossval is 0.88575
Std is 0.02374

## 5. Random forest

### a. Default regularization

1. Train a baseline model with the only parameters `n_estimators=50`, `max_depth=14`, `random_state=21`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model.
3. The format of the result of the code where you trained and evaluated the baseline model should be similar to what you have got for the logreg.

In [94]:
forest = RandomForestClassifier(n_estimators=50, max_depth=14, random_state=21)
crossval(forest, X_train, y_train)

train -  0.96455   |   valid -  0.88148
train -  0.96208   |   valid -  0.91852
train -  0.96785   |   valid -  0.86667
train -  0.96455   |   valid -  0.89630
train -  0.96538   |   valid -  0.91111
train -  0.96538   |   valid -  0.88148
train -  0.97115   |   valid -  0.91852
train -  0.96867   |   valid -  0.85185
train -  0.97364   |   valid -  0.88060
train -  0.97941   |   valid -  0.86567
Average accuracy on crossval is 0.88722
Std is 0.02204

### b. Optimizing regularization parameters

1. In the new cells try different values of the parameters `max_depth` and `n_estimators`.
2. As a bonus, play with other regularization parameters trying to find the best combination.

In [95]:
depth_values = [5, 10, 20, None]

forest_results_depth = []

for depth in depth_values:
    print(f"max_depth = {depth}")
    forest_model = RandomForestClassifier(
        n_estimators=50, #кол-во попыток и выборка из большего кол-ва
        max_depth=depth,
        random_state=21
    )
    
    score = crossval(forest_model, X_train, y_train)
    forest_results_depth.append({'max_depth': depth, 'accuracy': score})

max_depth = 5
train -  0.62984   |   valid -  0.58519
train -  0.57791   |   valid -  0.55556
train -  0.60181   |   valid -  0.57778
train -  0.59522   |   valid -  0.59259
train -  0.61748   |   valid -  0.57778
train -  0.59687   |   valid -  0.57778
train -  0.61500   |   valid -  0.60741
train -  0.59522   |   valid -  0.57037
train -  0.59967   |   valid -  0.57463
train -  0.60297   |   valid -  0.54478
Average accuracy on crossval is 0.57638
Std is 0.01668
max_depth = 10
train -  0.85408   |   valid -  0.75556
train -  0.85903   |   valid -  0.82963
train -  0.89777   |   valid -  0.80741
train -  0.90107   |   valid -  0.82222
train -  0.88376   |   valid -  0.85185
train -  0.87799   |   valid -  0.75556
train -  0.87222   |   valid -  0.82963
train -  0.86480   |   valid -  0.74074
train -  0.89456   |   valid -  0.82090
train -  0.87644   |   valid -  0.73881
Average accuracy on crossval is 0.79523
Std is 0.04051
max_depth = 20
train -  0.99505   |   valid -  0.88889
train -  0.99835   |   valid -  0.94815
train -  0.99670   |   valid -  0.88148
train -  0.99753   |   valid -  0.93333
train -  0.99505   |   valid -  0.91852
train -  0.99670   |   valid -  0.88889
train -  0.99753   |   valid -  0.91852
train -  0.99753   |   valid -  0.91111
train -  0.99753   |   valid -  0.92537
train -  0.99588   |   valid -  0.87313
Average accuracy on crossval is 0.90874
Std is 0.02330
max_depth = None
train -  1.00000   |   valid -  0.89630
train -  1.00000   |   valid -  0.94815
train -  1.00000   |   valid -  0.90370
train -  1.00000   |   valid -  0.93333
train -  1.00000   |   valid -  0.91111
train -  1.00000   |   valid -  0.89630
train -  1.00000   |   valid -  0.91852
train -  1.00000   |   valid -  0.90370
train -  1.00000   |   valid -  0.93284
train -  0.99918   |   valid -  0.89552
Average accuracy on crossval is 0.91395
Std is 0.01762

## 6. Predictions

1. Choose the best model and use it to make predictions for the test dataset.
2. Calculate the final accuracy.
3. Analyze: for which weekday your model makes the most errors (in % of the total number of samples of that class in your test dataset).
4. Save the model.

In [96]:
from sklearn.model_selection import GridSearchCV
import joblib

In [97]:
forest = RandomForestClassifier(n_estimators=50, random_state=21)

In [98]:
param_grid = {
    'criterion': ['gini', 'entropy'], #критерии качества
    'max_depth': np.arange(3, 21),
    'min_samples_split': [2, 3, 4] #разделение узлов
}

In [99]:
cv_forest = GridSearchCV( #кросс-валид
    forest, 
    param_grid, 
    scoring='accuracy', #метрика
    n_jobs=-1, #использовать все ядра процесса для более быстрого рез-та
    cv=10 #кол-во фолдов - 10 иттераций
)

In [100]:
cv_forest.fit(X_train, y_train)

GridSearchCV(cv=10,
             estimator=RandomForestClassifier(n_estimators=50, random_state=21),
             n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20]),
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [101]:
cv_forest.best_params_

{'criterion': 'entropy', 'max_depth': 18, 'min_samples_split': 2}

In [102]:
cv_forest.best_score_

0.9109563294637921

In [103]:
best_mod = cv_forest.best_estimator_
y_pred = best_mod.predict(X_test)
accuracy_score(y_test, y_pred)

0.9289940828402367

In [104]:
results = pd.DataFrame({
    'true': y_test.values,
    'pred': y_pred,
    'correct': y_test.values == y_pred
})

day_names = {0: 'Пн', 1: 'Вт', 2: 'Ср', 3: 'Чт', 4: 'Пт', 5: 'Сб', 6: 'Вс'}

error_rates = {}
for day in sorted(y_test.unique()):
    day_data = results[results['true'] == day]
    total = len(day_data)
    errors = (~day_data['correct']).sum()
    error_rate = errors / total * 100
    error_rates[day] = error_rate
    day_name = day_names.get(day, 0)
    print(f"{day_name}: {error_rate:.2f}% ошибок ({errors} из {total})")

max_error_day = max(error_rates, key=error_rates.get) # значение из словаря для каждого ключа -> вывод ключ
max_error_rate = error_rates[max_error_day]
max_error_name = day_names.get(max_error_day, 0)

print(f"наиб % ошибок: {max_error_name} (День {max_error_day})")
print(f"процент ошибок: {max_error_rate:.2f}%")

Пн: 22.22% ошибок (6 из 27)
Вт: 10.91% ошибок (6 из 55)
Ср: 6.67% ошибок (2 из 30)
Чт: 2.50% ошибок (2 из 80)
Пт: 14.29% ошибок (3 из 21)
Сб: 5.56% ошибок (3 из 54)
Вс: 2.82% ошибок (2 из 71)
наиб % ошибок: Пн (День 0)
процент ошибок: 22.22%

In [105]:
error_rates

{0: 22.22222222222222,
 1: 10.909090909090908,
 2: 6.666666666666667,
 3: 2.5,
 4: 14.285714285714285,
 5: 5.555555555555555,
 6: 2.8169014084507045}

In [106]:
day_data

     true  pred  correct
2       6     6     True
8       6     6     True
9       6     6     True
11      6     6     True
19      6     6     True
..    ...   ...      ...
301     6     6     True
302     6     6     True
306     6     6     True
312     6     6     True
330     6     6     True

[71 rows x 3 columns]

In [107]:
joblib.dump(best_mod, 'model.joblib')

['model.joblib']